### ISSUE TITLE
[oltp][mysql][v8.0] java.math.BigInteger cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by at15** [benchhub/forks#2]
- mysql 8.0

````
⇒  ./oltpbenchmark -b tpcc -c config/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o outputfile
16:58:55,016 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/sample_tpcc_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://localhost:3306/tpcc
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  2.0

16:58:55,017 (DBWorkload.java:260) INFO  - ======================================================================
16:58:55,026 (DBWorkload.java:519) INFO  - Creating new TPCC database...
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the tpcc database
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:251)
	at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:801)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:520)
Caused by: java.sql.SQLException: java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1041)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3496)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2460)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:119)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:247)
	... 2 more
Caused by: java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
	at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:992)
	... 18 more

````

on mysql end

````
mysql_1    | 2018-01-14T00:58:55.174995Z 17 [Note] Aborted connection 17 to db: 'tpcc' user: 'root' host: '172.20.0.1' (Got an error reading communication packets)
mysql_1    | 2018-01-14T01:10:41.730637Z 18 [Note] Aborted connection 18 to db: 'tpcc' user: 'root' host: '172.20.0.1' (Got an error reading communication packets)
````

**Comment by at15** [comment]
might related to mysql version?

**Comment by at15** [comment]
yep, using mysql5.7 worked ... 

````
⇒  ./oltpbenchmark -b tpcc -c config/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o outputfile
17:16:29,781 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/sample_tpcc_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://localhost:3306/tpcc
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  2.0

17:16:29,782 (DBWorkload.java:260) INFO  - ======================================================================
17:16:29,791 (DBWorkload.java:519) INFO  - Creating new TPCC database...
17:16:30,241 (DBWorkload.java:521) INFO  - Finished!
17:16:30,242 (DBWorkload.java:522) INFO  - ======================================================================
17:16:30,243 (DBWorkload.java:545) INFO  - Loading data into TPCC database...
17:17:18,703 (DBWorkload.java:547) INFO  - Finished!
17:17:18,704 (DBWorkload.java:548) INFO  - ======================================================================
17:17:18,705 (DBWorkload.java:813) INFO  - Creating 2 virtual terminals...
17:17:18,747 (DBWorkload.java:818) INFO  - Launching the TPCC Benchmark with 1 Phase...
17:17:18,751 (ThreadBench.java:327) INFO  - PHASE START :: [Workload=TPCC] [Serial=false] [Time=60] [WarmupTime=0] [Rate=10000] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]] [ActiveWorkers=2]
17:17:18,751 (ThreadBench.java:477) INFO  - MEASURE :: Warmup complete, starting measurements.
17:18:18,752 (ThreadBench.java:433) INFO  - TERMINATE :: Waiting for all terminals to finish ..
17:18:18,807 (ThreadBench.java:233) INFO  - Starting WatchDogThread
17:18:18,816 (DBWorkload.java:824) INFO  - ======================================================================
17:18:18,817 (DBWorkload.java:825) INFO  - Rate limited reqs/s: Results(nanoSeconds=60000597707, measuredRequests=20740) = 345.6632232445304 requests/sec
17:18:18,818 (DBWorkload.java:682) INFO  - Output Raw data into file: results/outputfile.csv
17:18:19,070 (DBWorkload.java:736) INFO  - Output into file: results/outputfile.res
17:18:19,070 (DBWorkload.java:739) INFO  - Grouped into Buckets of 5 seconds
````
[mysql5.7-01131721.zip](https://github.com/benchhub/forks/files/1628927/mysql5.7-01131721.zip)
