### ISSUE TITLE
[ycsb] Build and Redis

### ISSUE THREAD

**Issue by at15** [benchhub/forks#3]
- `mvn package -Dmaven.test.skip=true` otherwise it will start running test (took 3min to build ...)
  - might checkout travis to see how is test really tested on CI
- [x] why in its release, there are many jars with bindings? (not defined in pom?)  https://github.com/brianfrankcooper/YCSB/releases

> To build the full distribution, with all database bindings: mvn clean package
To build a single database binding: mvn -pl com.yahoo.ycsb:mongodb-binding -am clean package

- https://github.com/brianfrankcooper/YCSB/wiki/Getting-Started
- [ ] the `bin/ycsb` is using python2, but the shebang line is `env python`, which is `python3` (in most modern OS ...)
  - `env python2` seems work
- `./bin/ycsb.sh shell basic` still work ... guess they maintain the python and shell script at same time?
   - [ ] `Ctrl D` is not handled 

>  Exception in thread "main" java.lang.NullPointerException
	at com.yahoo.ycsb.CommandLine.main(CommandLine.java:123)

**Comment by at15** [comment]
guess there is problem about classpath ... the python script might work?

````
⇒  ./bin/ycsb.sh load basic -P workloads/workloada 
/usr/lib/jvm/jdk1.8.0_121/bin/java  -classpath /home/at15/workspace/src/github.com/benchhub/ycsb/conf:/home/at15/workspace/src/github.com/benchhub/ycsb/core/target/core-0.14.0-SNAPSHOT.jar:/home/at15/workspace/src/github.com/benchhub/ycsb/core/target/core-0.14.0-SNAPSHOT.jar com.yahoo.ycsb.Client -load -db com.yahoo.ycsb.BasicDB -P workloads/workloada
Command line: -load -db com.yahoo.ycsb.BasicDB -P workloads/workloadaYCSB Client 0.14.0-SNAPSHOT

Loading workload...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/htrace/core/Tracer$Builder
	at com.yahoo.ycsb.Client.getTracer(Client.java:902)
	at com.yahoo.ycsb.Client.main(Client.java:751)
Caused by: java.lang.ClassNotFoundException: org.apache.htrace.core.Tracer$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
 (might take a few minutes for large data sets)
````

**Comment by at15** [comment]
using python2  seems work ... but the output it pretty strange ... or it is the case after all .... 

````
INSERT usertable user8295266226408665858 [ field1=8@o>*8 Bw?:v Fs#X}? . (*+T}.]k=/f7[-$&8=/6"Mw>>v*Kq:Ck(5x79`0:")P=#Nu;N)>:t*72#;",/26U7-&64.<0-n!Fw; field0=**,=I7;;f?Ao<3.0E;1+d?8,7%6<:v-"f:-r64: I{'_/4F? F/4J73Im&8,8B--G-'L'1A#$8$8.x&Ps7.`8E-0Xy9!p/N/']q7 field7=? x.A9*(n?4|7I'(8b:L=43n1Zu+]i-7.0U}()h.K)?X'<^o9P-5O(S-!7z.Km;]w,4z#[q4Hc>Zy/R/)M/;Uq"+".Z9-@?0M=- field6=+7|>!|*'($($0Yg;_;&Aa/229V/)B!,@m6Y1=^=!S7'Ey*"f2Q?-Ry V%)',#%j>L5^e'Iw,?|:Io'.v6-x9#r+A343`:'"?+,$ field9=6& 5Hw#".$'r!C15O'+F5(F}.E-4A-3J{/L?"6")\s8!p+6x*3`/^53!8$7,>+t.3r>(l3Ay7@/0>x!=(!['/_1$(v'#v7Nu)Ts' field8=:^9)X?6F3!Ge3+v;P{,#h&,b;P;$/8/Lm'Tc;9t&^!9T3-+<$#,12r%Du6G!8]5%Ly*-6(1l>+0%=&'7<-Y%%L=(\9/&& @!?)*< field3=;,l+^5#^-9Kk#Oa&@q-(09_y2K! Ms<!p: d:U-1H- Eu2Yg>40 ,d*^7$>~<]e&C'+8b>*> ;z'$j9't.@a6=.-!b<?v?X)%P-- field2=+'>!O5/Gu7,2"J%-".2P&>:<3t2Cc:;j:&x/Dm*De>E%-=<%]y'<n*Fi?%j?+&1]- E) Vw%I+68+$,$Ea8>4-A?(E'95*=Bu& field5=/Uk>(830d;$b3R5(4~;[)53 &6h+[u;@=44`:8:%Z-;>p6Xq2$r#(.4Rq>Z!+I{3*")Uy>00:Nw#Kw>&: B-:Z}3Vg*^o:M1>Km: field4=:Xy7Ew:"20Wa<W/55*+^9!&",; 8B%'I7,Gw;Y#=J10@--Ja":. Q'&V/(%n&C95Ky1[y?;h5Z!(:v0Y}:7:"Y?)4(:Gw.G{.A75 ]
INSERT usertable user2071219101098386137 [ field1=<R?5[!(^/!&.?C/01z7Dm;@1 0n.&(++x2 .-4t;P)$^>Os5/$!-<#Zk"Uo*Si&Ik!Pg*M#Ce3,z1Le/%|"Dg3=:1:z;1<)',( field0=>W5=@k;V)0,r:$|6=|-5t2B'Y'-U}#Z/<):->(!Jo4]a/]';*.=Lg)&t?8j)R!%*(2+2(%j"]{/U/-Cq#;l!Lq3\+$5.!H-!Pu* field7=:H),=d;.p6: >R{7]k=O!!Rq4V#$W);^g/4n?B#4J=<Rc/$f-I7-98 \1 ];,U91W729f'5f=Gs6:b.O=$;p;Bu?]y;0f'\w1J!1 field6=,Jq> r/My#^w$V7,-&#=.46:/Ws#]7%K1-Ck0="('l+Z9 ^c7=2%Pg-:v?R-990=C+5!.(Nq9Uu60 ;@!)S/3F9=@m4Fq2Ua>P-= field9=>3|2B84v>I'6:h>%x*Rs:982K#)<6 8.%G#908->0 :h"H)2^w?Pq/70$$&=:d&$4$B#-H%0I{&'04?z'=~9!8  8!N32.(_?- field8=/6h*B{3Vu?[g-K#<S92C14Fq41x7J7+^y6Zi*Ee6R18O1%Go.N-0T)7W1 K{/I%8Y(!(). &,:89j5:($#2'?0%@!*2~'.z$(:$ field3==1z**08P7-)<4\'5!p5;d2;06."<Z9(Fk&Q9=%2<&l.\!9,8*Vy&D{;26)+x/6z2]%1>*1>~=)~"Ca T/Rq!Zg#P9/X}*Ki:G14 field2=.B!-Uw$*~'4v-I/!%r/'(49`)U39+f=B7!Zs*Aa#/8;. )6l*Wo3# 3!*,'r Ki:/&%B/,%4?- ,H+*Ms?8t)X/-'6/-|*5(.R11 field5=/)((@1$0n+3~+H'-*h =0<?25R?$M)9^90=|.3|"N5=!,-X#!%$ 9p:G'3<#Pa/2d2 $5_%!Mu/-z+:z&E1!R{3J?;D6Fi#B+  field4=$'85B/ K54Je=92-Xw#Ka3V/5X{;C3(Pk._%3Om#Lo%-b>).*M'%M;+Z3J-1:98p$$r6S!/S{7"b5>~3>64/h/O+E1 W!6G%5 ]
[OVERALL], RunTime(ms), 2103
[OVERALL], Throughput(ops/sec), 475.51117451260103
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
````

> If you used BasicDB, you would see the insert statements for the database. If you used a real DB interface layer, the records would be loaded into the database

**Comment by at15** [comment]
can run it against redis 

first load

````
./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379" > outputLoad.txt

Loading workload...
Starting test.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2018-01-14 11:46:39:499 0 sec: 0 operations; est completion in 0 second 
2018-01-14 11:46:39:625 0 sec: 1000 operations; 7142.86 current ops/sec; [CLEANUP: Count=1, Max=89, Min=89, Avg=89, 90=89, 99=89, 99.9=89, 99.99=89] [INSERT: Count=1000, Max=3641, Min=66, Avg=110.12, 90=156, 99=257, 99.9=599, 99.99=3641] 
````

<details><summary>outputLoad.txt</summary><p>

````
[OVERALL], RunTime(ms), 140
[OVERALL], Throughput(ops/sec), 7142.857142857143
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 89.0
[CLEANUP], MinLatency(us), 89
[CLEANUP], MaxLatency(us), 89
[CLEANUP], 95thPercentileLatency(us), 89
[CLEANUP], 99thPercentileLatency(us), 89
[CLEANUP], 89, 1.0
[INSERT], Operations, 1000
[INSERT], AverageLatency(us), 110.124
[INSERT], MinLatency(us), 66
[INSERT], MaxLatency(us), 3641
[INSERT], 95thPercentileLatency(us), 184
[INSERT], 99thPercentileLatency(us), 257
[INSERT], Return=OK, 1000
[INSERT], 66, 2.0
[INSERT], 67, 18.0
[INSERT], 68, 21.0
[INSERT], 69, 9.0
[INSERT], 70, 12.0
[INSERT], 71, 32.0
[INSERT], 72, 23.0
[INSERT], 73, 30.0
[INSERT], 74, 42.0
[INSERT], 75, 32.0
[INSERT], 76, 39.0
[INSERT], 77, 25.0
[INSERT], 78, 26.0
[INSERT], 79, 8.0
[INSERT], 80, 13.0
[INSERT], 81, 14.0
[INSERT], 82, 11.0
[INSERT], 83, 19.0
[INSERT], 84, 13.0
[INSERT], 85, 11.0
[INSERT], 86, 8.0
[INSERT], 87, 7.0
[INSERT], 88, 22.0
[INSERT], 89, 18.0
[INSERT], 90, 17.0
[INSERT], 91, 16.0
[INSERT], 92, 17.0
[INSERT], 93, 8.0
[INSERT], 94, 8.0
[INSERT], 95, 13.0
[INSERT], 96, 5.0
[INSERT], 97, 8.0
[INSERT], 98, 5.0
[INSERT], 99, 6.0
[INSERT], 100, 17.0
[INSERT], 101, 11.0
[INSERT], 102, 9.0
[INSERT], 103, 6.0
[INSERT], 104, 10.0
[INSERT], 105, 10.0
[INSERT], 106, 1.0
[INSERT], 107, 10.0
[INSERT], 108, 7.0
[INSERT], 109, 9.0
[INSERT], 110, 11.0
[INSERT], 111, 6.0
[INSERT], 112, 12.0
[INSERT], 113, 8.0
[INSERT], 114, 7.0
[INSERT], 115, 6.0
[INSERT], 116, 8.0
[INSERT], 117, 13.0
[INSERT], 118, 10.0
[INSERT], 119, 13.0
[INSERT], 120, 5.0
[INSERT], 121, 1.0
[INSERT], 122, 7.0
[INSERT], 123, 10.0
[INSERT], 124, 6.0
[INSERT], 125, 4.0
[INSERT], 126, 5.0
[INSERT], 127, 2.0
[INSERT], 128, 2.0
[INSERT], 129, 3.0
[INSERT], 130, 2.0
[INSERT], 131, 5.0
[INSERT], 132, 3.0
[INSERT], 133, 3.0
[INSERT], 134, 4.0
[INSERT], 135, 4.0
[INSERT], 136, 7.0
[INSERT], 137, 4.0
[INSERT], 138, 6.0
[INSERT], 139, 4.0
[INSERT], 140, 1.0
[INSERT], 141, 4.0
[INSERT], 142, 5.0
[INSERT], 143, 3.0
[INSERT], 144, 6.0
[INSERT], 145, 5.0
[INSERT], 146, 7.0
[INSERT], 147, 2.0
[INSERT], 148, 4.0
[INSERT], 149, 3.0
[INSERT], 150, 3.0
[INSERT], 151, 7.0
[INSERT], 152, 4.0
[INSERT], 153, 4.0
[INSERT], 154, 4.0
[INSERT], 155, 3.0
[INSERT], 156, 6.0
[INSERT], 157, 5.0
[INSERT], 158, 2.0
[INSERT], 159, 1.0
[INSERT], 160, 5.0
[INSERT], 161, 2.0
[INSERT], 162, 3.0
[INSERT], 163, 4.0
[INSERT], 164, 4.0
[INSERT], 165, 1.0
[INSERT], 166, 1.0
[INSERT], 167, 1.0
[INSERT], 170, 2.0
[INSERT], 171, 1.0
[INSERT], 172, 1.0
[INSERT], 173, 2.0
[INSERT], 174, 3.0
[INSERT], 175, 3.0
[INSERT], 177, 1.0
[INSERT], 178, 1.0
[INSERT], 180, 3.0
[INSERT], 181, 1.0
[INSERT], 183, 2.0
[INSERT], 184, 2.0
[INSERT], 185, 1.0
[INSERT], 186, 1.0
[INSERT], 187, 1.0
[INSERT], 188, 1.0
[INSERT], 189, 1.0
[INSERT], 191, 1.0
[INSERT], 192, 2.0
[INSERT], 196, 1.0
[INSERT], 198, 1.0
[INSERT], 202, 3.0
[INSERT], 207, 2.0
[INSERT], 209, 2.0
[INSERT], 211, 1.0
[INSERT], 212, 1.0
[INSERT], 215, 1.0
[INSERT], 216, 1.0
[INSERT], 218, 3.0
[INSERT], 221, 1.0
[INSERT], 222, 2.0
[INSERT], 223, 2.0
[INSERT], 225, 1.0
[INSERT], 230, 1.0
[INSERT], 231, 1.0
[INSERT], 233, 1.0
[INSERT], 237, 2.0
[INSERT], 243, 1.0
[INSERT], 248, 2.0
[INSERT], 257, 1.0
[INSERT], 258, 1.0
[INSERT], 269, 1.0
[INSERT], 305, 1.0
[INSERT], 323, 1.0
[INSERT], 330, 1.0
[INSERT], 335, 1.0
[INSERT], 339, 1.0
[INSERT], 362, 1.0
[INSERT], 599, 1.0
[INSERT], 3641, 1.0
````
</p></details>

then run 

````
⇒  ./bin/ycsb run redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=6379" > outputRun.txt

Loading workload...
Starting test.
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2018-01-14 11:51:58:344 0 sec: 0 operations; est completion in 0 second 
2018-01-14 11:51:58:433 0 sec: 1000 operations; 9615.38 current ops/sec; [READ: Count=487, Max=4807, Min=36, Avg=71.87, 90=92, 99=228, 99.9=4807, 99.99=4807] [CLEANUP: Count=1, Max=75, Min=75, Avg=75, 90=75, 99=75, 99.9=75, 99.99=75] [UPDATE: Count=513, Max=467, Min=40, Avg=65.8, 90=90, 99=173, 99.9=302, 99.99=467] 
````
<details><summary>outputRun.txt</summary><p>

````
[OVERALL], RunTime(ms), 104
[OVERALL], Throughput(ops/sec), 9615.384615384615
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
[READ], Operations, 487
[READ], AverageLatency(us), 71.86858316221766
[READ], MinLatency(us), 36
[READ], MaxLatency(us), 4807
[READ], 95thPercentileLatency(us), 118
[READ], 99thPercentileLatency(us), 228
[READ], Return=OK, 487
[READ], 36, 8.0
[READ], 37, 18.0
[READ], 38, 14.0
[READ], 39, 13.0
[READ], 40, 17.0
[READ], 41, 9.0
[READ], 42, 11.0
[READ], 43, 6.0
[READ], 44, 10.0
[READ], 45, 12.0
[READ], 46, 11.0
[READ], 47, 10.0
[READ], 48, 13.0
[READ], 49, 14.0
[READ], 50, 19.0
[READ], 51, 18.0
[READ], 52, 20.0
[READ], 53, 15.0
[READ], 54, 28.0
[READ], 55, 23.0
[READ], 56, 16.0
[READ], 57, 13.0
[READ], 58, 7.0
[READ], 59, 11.0
[READ], 60, 2.0
[READ], 61, 2.0
[READ], 62, 4.0
[READ], 63, 3.0
[READ], 64, 10.0
[READ], 65, 5.0
[READ], 66, 2.0
[READ], 67, 8.0
[READ], 68, 2.0
[READ], 69, 8.0
[READ], 70, 5.0
[READ], 71, 7.0
[READ], 72, 3.0
[READ], 73, 2.0
[READ], 74, 3.0
[READ], 75, 1.0
[READ], 76, 1.0
[READ], 77, 1.0
[READ], 78, 3.0
[READ], 79, 2.0
[READ], 81, 1.0
[READ], 82, 3.0
[READ], 83, 2.0
[READ], 84, 1.0
[READ], 85, 1.0
[READ], 86, 4.0
[READ], 87, 2.0
[READ], 88, 2.0
[READ], 89, 4.0
[READ], 90, 2.0
[READ], 91, 4.0
[READ], 92, 3.0
[READ], 93, 2.0
[READ], 94, 2.0
[READ], 95, 1.0
[READ], 97, 1.0
[READ], 98, 1.0
[READ], 99, 1.0
[READ], 100, 1.0
[READ], 101, 1.0
[READ], 102, 3.0
[READ], 104, 1.0
[READ], 106, 1.0
[READ], 107, 3.0
[READ], 108, 1.0
[READ], 109, 3.0
[READ], 117, 1.0
[READ], 118, 1.0
[READ], 119, 1.0
[READ], 120, 1.0
[READ], 121, 1.0
[READ], 122, 1.0
[READ], 125, 1.0
[READ], 128, 1.0
[READ], 131, 1.0
[READ], 135, 1.0
[READ], 137, 1.0
[READ], 144, 2.0
[READ], 148, 1.0
[READ], 152, 1.0
[READ], 161, 1.0
[READ], 166, 1.0
[READ], 174, 1.0
[READ], 181, 1.0
[READ], 193, 1.0
[READ], 228, 1.0
[READ], 238, 1.0
[READ], 252, 2.0
[READ], 369, 1.0
[READ], 4807, 1.0
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 75.0
[CLEANUP], MinLatency(us), 75
[CLEANUP], MaxLatency(us), 75
[CLEANUP], 95thPercentileLatency(us), 75
[CLEANUP], 99thPercentileLatency(us), 75
[CLEANUP], 75, 1.0
[UPDATE], Operations, 513
[UPDATE], AverageLatency(us), 65.79922027290448
[UPDATE], MinLatency(us), 40
[UPDATE], MaxLatency(us), 467
[UPDATE], 95thPercentileLatency(us), 100
[UPDATE], 99thPercentileLatency(us), 173
[UPDATE], Return=OK, 513
[UPDATE], 40, 1.0
[UPDATE], 41, 5.0
[UPDATE], 42, 16.0
[UPDATE], 43, 18.0
[UPDATE], 44, 15.0
[UPDATE], 45, 10.0
[UPDATE], 46, 13.0
[UPDATE], 47, 5.0
[UPDATE], 48, 10.0
[UPDATE], 49, 4.0
[UPDATE], 50, 11.0
[UPDATE], 51, 12.0
[UPDATE], 52, 12.0
[UPDATE], 53, 15.0
[UPDATE], 54, 22.0
[UPDATE], 55, 21.0
[UPDATE], 56, 25.0
[UPDATE], 57, 17.0
[UPDATE], 58, 24.0
[UPDATE], 59, 21.0
[UPDATE], 60, 13.0
[UPDATE], 61, 11.0
[UPDATE], 62, 10.0
[UPDATE], 63, 6.0
[UPDATE], 64, 6.0
[UPDATE], 65, 9.0
[UPDATE], 66, 11.0
[UPDATE], 67, 10.0
[UPDATE], 68, 4.0
[UPDATE], 69, 8.0
[UPDATE], 70, 5.0
[UPDATE], 71, 6.0
[UPDATE], 72, 9.0
[UPDATE], 73, 9.0
[UPDATE], 74, 7.0
[UPDATE], 75, 5.0
[UPDATE], 76, 4.0
[UPDATE], 77, 4.0
[UPDATE], 78, 1.0
[UPDATE], 79, 5.0
[UPDATE], 80, 2.0
[UPDATE], 81, 2.0
[UPDATE], 82, 9.0
[UPDATE], 83, 4.0
[UPDATE], 84, 4.0
[UPDATE], 85, 6.0
[UPDATE], 86, 4.0
[UPDATE], 87, 6.0
[UPDATE], 88, 3.0
[UPDATE], 89, 1.0
[UPDATE], 90, 5.0
[UPDATE], 93, 1.0
[UPDATE], 94, 4.0
[UPDATE], 95, 4.0
[UPDATE], 96, 1.0
[UPDATE], 97, 3.0
[UPDATE], 98, 2.0
[UPDATE], 99, 3.0
[UPDATE], 100, 3.0
[UPDATE], 101, 1.0
[UPDATE], 102, 1.0
[UPDATE], 103, 1.0
[UPDATE], 107, 2.0
[UPDATE], 108, 1.0
[UPDATE], 110, 3.0
[UPDATE], 112, 1.0
[UPDATE], 113, 1.0
[UPDATE], 117, 1.0
[UPDATE], 121, 1.0
[UPDATE], 127, 1.0
[UPDATE], 128, 1.0
[UPDATE], 129, 1.0
[UPDATE], 133, 1.0
[UPDATE], 141, 1.0
[UPDATE], 146, 1.0
[UPDATE], 159, 1.0
[UPDATE], 173, 1.0
[UPDATE], 176, 1.0
[UPDATE], 182, 1.0
[UPDATE], 204, 1.0
[UPDATE], 302, 1.0
[UPDATE], 467, 1.0
````
</p></details>

<details><summary>Redis server output (suggest disable Transparent Huge Pages)</summary><p>

````
redis_1  | 1:C 14 Jan 19:44:04.975 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 14 Jan 19:44:04.975 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 14 Jan 19:44:04.975 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 14 Jan 19:44:04.976 * Running mode=standalone, port=6379.
redis_1  | 1:M 14 Jan 19:44:04.976 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1  | 1:M 14 Jan 19:44:04.976 # Server initialized
redis_1  | 1:M 14 Jan 19:44:04.976 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 14 Jan 19:44:04.977 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1  | 1:M 14 Jan 19:44:04.977 * Ready to accept connections
redis_1  | 1:M 14 Jan 19:49:05.004 * 100 changes in 300 seconds. Saving...
redis_1  | 1:M 14 Jan 19:49:05.004 * Background saving started by pid 18
redis_1  | 18:C 14 Jan 19:49:05.027 * DB saved on disk
redis_1  | 18:C 14 Jan 19:49:05.027 * RDB: 8 MB of memory used by copy-on-write
redis_1  | 1:M 14 Jan 19:49:05.105 * Background saving terminated with success
redis_1  | 1:M 14 Jan 19:54:06.094 * 100 changes in 300 seconds. Saving...
redis_1  | 1:M 14 Jan 19:54:06.095 * Background saving started by pid 19
redis_1  | 19:C 14 Jan 19:54:06.117 * DB saved on disk
redis_1  | 19:C 14 Jan 19:54:06.117 * RDB: 8 MB of memory used by copy-on-write
redis_1  | 1:M 14 Jan 19:54:06.195 * Background saving terminated with success
````
</p></details>

**Comment by at15** [comment]
@gaocegege an example of using `details` tag
