### ISSUE TITLE
[oltp] Result folder is not created if not exists

### ISSUE THREAD

**Issue by at15** [benchhub/forks#4]
`$(B) -b tpcc -c $(BCONF)/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o result/tpcc.log`

````java
Exception in thread "main" java.io.FileNotFoundException: results/result/tpcc.log.csv (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintStream.<init>(PrintStream.java:279)
	at com.oltpbenchmark.DBWorkload.writeOutputs(DBWorkload.java:681)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:579)
Makefile:28: recipe for target 'tpcc' failed
`````

so when `-o dst` is specified ... it will output to `results/${dst}.csv` instead of `${dst}` ...

**Comment by at15** [comment]
so without folder it worked ...

````
⇒  make tpcc      
cd ..; ./oltpbenchmark -b tpcc -c config/benchmarks/sample_tpcc_config.xml --create=true --load=true --execute=true -s 5 -o tpcc.log
18:25:26,524 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/benchmarks/sample_tpcc_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://localhost:3306/tpcc
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  2.0

18:25:26,526 (DBWorkload.java:260) INFO  - ======================================================================
18:25:26,534 (DBWorkload.java:519) INFO  - Creating new TPCC database...
18:25:27,169 (DBWorkload.java:521) INFO  - Finished!
18:25:27,170 (DBWorkload.java:522) INFO  - ======================================================================
18:25:27,170 (DBWorkload.java:545) INFO  - Loading data into TPCC database...
18:26:24,212 (DBWorkload.java:547) INFO  - Finished!
18:26:24,212 (DBWorkload.java:548) INFO  - ======================================================================
18:26:24,212 (DBWorkload.java:813) INFO  - Creating 2 virtual terminals...
18:26:24,229 (DBWorkload.java:818) INFO  - Launching the TPCC Benchmark with 1 Phase...
18:26:24,232 (ThreadBench.java:327) INFO  - PHASE START :: [Workload=TPCC] [Serial=false] [Time=60] [WarmupTime=0] [Rate=10000] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]] [ActiveWorkers=2]
18:26:24,233 (ThreadBench.java:477) INFO  - MEASURE :: Warmup complete, starting measurements.
18:27:24,235 (ThreadBench.java:433) INFO  - TERMINATE :: Waiting for all terminals to finish ..
18:27:24,301 (ThreadBench.java:233) INFO  - Starting WatchDogThread
18:27:24,322 (DBWorkload.java:824) INFO  - ======================================================================
18:27:24,322 (DBWorkload.java:825) INFO  - Rate limited reqs/s: Results(nanoSeconds=60000896422, measuredRequests=19497) = 324.94514520038416 requests/sec
18:27:24,323 (DBWorkload.java:682) INFO  - Output Raw data into file: results/tpcc.log.csv
18:27:24,554 (DBWorkload.java:736) INFO  - Output into file: results/tpcc.log.res
18:27:24,554 (DBWorkload.java:739) INFO  - Grouped into Buckets of 5 seconds
````
